# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

linpredcompute <- function(X, nsites, p, beta, offset) {
    .Call(`_CARBayesST_linpredcompute`, X, nsites, p, beta, offset)
}

quadform <- function(Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho) {
    .Call(`_CARBayesST_quadform`, Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho)
}

poissonbetaupdateMALA <- function(X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayesST_poissonbetaupdateMALA`, X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

poissonbetaupdateRW <- function(X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayesST_poissonbetaupdateRW`, X, nsites, p, beta, offset, y, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

poissoncarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset) {
    .Call(`_CARBayesST_poissoncarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset)
}

poissoncarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset) {
    .Call(`_CARBayesST_poissoncarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset)
}

poissonindepupdateMALA <- function(nsites, theta, sigma2, y, theta_tune, offset) {
    .Call(`_CARBayesST_poissonindepupdateMALA`, nsites, theta, sigma2, y, theta_tune, offset)
}

poissonindepupdateRW <- function(nsites, theta, tau2, y, theta_tune, offset) {
    .Call(`_CARBayesST_poissonindepupdateRW`, nsites, theta, tau2, y, theta_tune, offset)
}

zipcarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset, missind) {
    .Call(`_CARBayesST_zipcarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset, missind)
}

zipcarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset, missind) {
    .Call(`_CARBayesST_zipcarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, phi_tune, rho, offset, ntime, mult_offset, missind)
}

zipindepupdateMALA <- function(nsites, theta, sigma2, y, theta_tune, offset, missind) {
    .Call(`_CARBayesST_zipindepupdateMALA`, nsites, theta, sigma2, y, theta_tune, offset, missind)
}

zipindepupdateRW <- function(nsites, theta, tau2, y, theta_tune, offset, missind) {
    .Call(`_CARBayesST_zipindepupdateRW`, nsites, theta, tau2, y, theta_tune, offset, missind)
}

binomialbetaupdateMALA <- function(X, nsites, p, beta, offset, y, failures, trials, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayesST_binomialbetaupdateMALA`, X, nsites, p, beta, offset, y, failures, trials, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

binomialbetaupdateRW <- function(X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call(`_CARBayesST_binomialbetaupdateRW`, X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

binomialindepupdateMALA <- function(nsites, theta, sigma2, y, failures, trials, theta_tune, offset) {
    .Call(`_CARBayesST_binomialindepupdateMALA`, nsites, theta, sigma2, y, failures, trials, theta_tune, offset)
}

binomialindepupdateRW <- function(nsites, theta, tau2, y, failures, theta_tune, offset) {
    .Call(`_CARBayesST_binomialindepupdateRW`, nsites, theta, tau2, y, failures, theta_tune, offset)
}

binomialcarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, trials, phi_tune, rho, offset, ntime, mult_offset) {
    .Call(`_CARBayesST_binomialcarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, trials, phi_tune, rho, offset, ntime, mult_offset)
}

binomialcarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, phi_tune, rho, offset, ntime, mult_offset) {
    .Call(`_CARBayesST_binomialcarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, y, failures, phi_tune, rho, offset, ntime, mult_offset)
}

gaussiancarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, nu2, offset, rho, ntime) {
    .Call(`_CARBayesST_gaussiancarupdate`, Wtriplet, Wbegfin, Wtripletsum, nsites, phi, tau2, nu2, offset, rho, ntime)
}

poissonarcarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset) {
    .Call(`_CARBayesST_poissonarcarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset)
}

poissonarcarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset) {
    .Call(`_CARBayesST_poissonarcarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset)
}

ziparcarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset, missind) {
    .Call(`_CARBayesST_ziparcarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset, missind)
}

ziparcarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset, missind) {
    .Call(`_CARBayesST_ziparcarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, phi_tune, offset, denoffset, missind)
}

gammaquadformcompute <- function(Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho) {
    .Call(`_CARBayesST_gammaquadformcompute`, Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho)
}

tauquadformcompute <- function(Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho, gamma) {
    .Call(`_CARBayesST_tauquadformcompute`, Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho, gamma)
}

binomialarcarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, failuresmat, trialsmat, phi_tune, offset, denoffset) {
    .Call(`_CARBayesST_binomialarcarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, failuresmat, trialsmat, phi_tune, offset, denoffset)
}

binomialarcarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, failuresmat, phi_tune, offset, denoffset) {
    .Call(`_CARBayesST_binomialarcarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, gamma, rho, ymat, failuresmat, phi_tune, offset, denoffset)
}

gaussianarcarupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, nu2, gamma, rho, offset, denoffset) {
    .Call(`_CARBayesST_gaussianarcarupdate`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, tau2, nu2, gamma, rho, offset, denoffset)
}

qform <- function(Qtrip, phi) {
    .Call(`_CARBayesST_qform`, Qtrip, phi)
}

qform_asym <- function(Qtrip, phi1, phi2) {
    .Call(`_CARBayesST_qform_asym`, Qtrip, phi1, phi2)
}

qformSPACETIME <- function(Qtrip, phi, ntime, nsite) {
    .Call(`_CARBayesST_qformSPACETIME`, Qtrip, phi, ntime, nsite)
}

SPTICARphiGaussian <- function(W, nsites, ntimes, phi, nneighbours, tau, lik_var, y, alpha, XB) {
    .Call(`_CARBayesST_SPTICARphiGaussian`, W, nsites, ntimes, phi, nneighbours, tau, lik_var, y, alpha, XB)
}

qform_difference_ST <- function(Qtrip, Qtime, phi, nsites) {
    .Call(`_CARBayesST_qform_difference_ST`, Qtrip, Qtime, phi, nsites)
}

qform_ST <- function(Qspace, Qtime, phi, nsites) {
    .Call(`_CARBayesST_qform_ST`, Qspace, Qtime, phi, nsites)
}

qform_ST_asym <- function(Qspace, Qtime, phi1, phi2, nsites) {
    .Call(`_CARBayesST_qform_ST_asym`, Qspace, Qtime, phi1, phi2, nsites)
}

update_Qtime <- function(Qtime, alpha, rowNumberLastDiag) {
    .Call(`_CARBayesST_update_Qtime`, Qtime, alpha, rowNumberLastDiag)
}

updatetriplets_rho <- function(trips, nsites, rho_old, rho_new, fixedridge) {
    .Call(`_CARBayesST_updatetriplets_rho`, trips, nsites, rho_old, rho_new, fixedridge)
}

updatetripList2 <- function(trips, vold, vnew, nedges, nsites, block, block_length, rho, fixedridge) {
    .Call(`_CARBayesST_updatetripList2`, trips, vold, vnew, nedges, nsites, block, block_length, rho, fixedridge)
}

Zupdatesqbin <- function(Z, Offset, Y, delta, lambda, nsites, ntime, G, SS, prioroffset, Gstar, failures) {
    .Call(`_CARBayesST_Zupdatesqbin`, Z, Offset, Y, delta, lambda, nsites, ntime, G, SS, prioroffset, Gstar, failures)
}

Zupdatesqpoi <- function(Z, Offset, Y, delta, lambda, nsites, ntime, G, SS, prioroffset, Gstar) {
    .Call(`_CARBayesST_Zupdatesqpoi`, Z, Offset, Y, delta, lambda, nsites, ntime, G, SS, prioroffset, Gstar)
}

Zupdatesqgau <- function(Z, Offset, delta, lambda, nsites, ntime, G, SS, prioroffset, Gstar, nu2) {
    .Call(`_CARBayesST_Zupdatesqgau`, Z, Offset, delta, lambda, nsites, ntime, G, SS, prioroffset, Gstar, nu2)
}

tau2compute <- function(tau2, temp, tau2_shape, prior_tau2, N) {
    .Call(`_CARBayesST_tau2compute`, tau2, temp, tau2_shape, prior_tau2, N)
}

rhoquadformcompute <- function(Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho, tau2) {
    .Call(`_CARBayesST_rhoquadformcompute`, Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho, tau2)
}

binomialsrecarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, y, failures, trials, phi_tune, offset, denoffset, tau2) {
    .Call(`_CARBayesST_binomialsrecarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, y, failures, trials, phi_tune, offset, denoffset, tau2)
}

binomialsrecarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, ymat, failuresmat, phi_tune, offset, denoffset, tau2) {
    .Call(`_CARBayesST_binomialsrecarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, ymat, failuresmat, phi_tune, offset, denoffset, tau2)
}

poissonsrecarupdateMALA <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, ymat, phi_tune, offset, denoffset, tau2) {
    .Call(`_CARBayesST_poissonsrecarupdateMALA`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, ymat, phi_tune, offset, denoffset, tau2)
}

poissonsrecarupdateRW <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, ymat, phi_tune, offset, denoffset, tau2) {
    .Call(`_CARBayesST_poissonsrecarupdateRW`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntime, phi, rho, ymat, phi_tune, offset, denoffset, tau2)
}

tauquadformcompute2 <- function(Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho) {
    .Call(`_CARBayesST_tauquadformcompute2`, Wtriplet, Wtripletsum, n_triplet, nsites, ntime, phi, rho)
}

SPTICARphiVarbMALA <- function(W, nsites, ntimes, phiVarb, nneighbours, tau, y, E, phiVarb_tune, alpha, XB) {
    .Call(`_CARBayesST_SPTICARphiVarbMALA`, W, nsites, ntimes, phiVarb, nneighbours, tau, y, E, phiVarb_tune, alpha, XB)
}

SPTICARphiBinomialMALA <- function(W, nsites, ntimes, phi, nneighbours, tau, y, alpha, XB, phiVarb_tune, trials) {
    .Call(`_CARBayesST_SPTICARphiBinomialMALA`, W, nsites, ntimes, phi, nneighbours, tau, y, alpha, XB, phiVarb_tune, trials)
}

SPTICARphiBinomial <- function(W, nsites, ntimes, phi, nneighbours, tau, y, alpha, XB, phiVarb_tune, trials) {
    .Call(`_CARBayesST_SPTICARphiBinomial`, W, nsites, ntimes, phi, nneighbours, tau, y, alpha, XB, phiVarb_tune, trials)
}

SPTICARphiVarb <- function(W, nsites, ntimes, phiVarb, nneighbours, tau, y, E, phiVarb_tune, alpha, XB) {
    .Call(`_CARBayesST_SPTICARphiVarb`, W, nsites, ntimes, phiVarb, nneighbours, tau, y, E, phiVarb_tune, alpha, XB)
}

tempupdate <- function(Nchains, dt) {
    .Call(`_CARBayesST_tempupdate`, Nchains, dt)
}

matcomp <- function(X, beta, prop, p, Nchains) {
    .Call(`_CARBayesST_matcomp`, X, beta, prop, p, Nchains)
}

offsetcompute <- function(w, gamma, time, Nchains, nsites, Ntrends, begin) {
    .Call(`_CARBayesST_offsetcompute`, w, gamma, time, Nchains, nsites, Ntrends, begin)
}

matN <- function(x, nsites, Nchains) {
    .Call(`_CARBayesST_matN`, x, nsites, Nchains)
}

linpredcomputeNchains <- function(X, nsites, p, beta, Nchains) {
    .Call(`_CARBayesST_linpredcomputeNchains`, X, nsites, p, beta, Nchains)
}

gammaproposal <- function(Nchains, gamma, gamma_tune, prior_vargamma, Wareas, trend, knots) {
    .Call(`_CARBayesST_gammaproposal`, Nchains, gamma, gamma_tune, prior_vargamma, Wareas, trend, knots)
}

lambdaupdate <- function(Nchains, temp) {
    .Call(`_CARBayesST_lambdaupdate`, Nchains, temp)
}

tau2quadform <- function(Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho, Nchains) {
    .Call(`_CARBayesST_tau2quadform`, Wtriplet, Wtripletsum, n_triplet, nsites, phi, theta, rho, Nchains)
}

tau2computeNchains <- function(temp, tau2_shape, prior_tau2, Nchains) {
    .Call(`_CARBayesST_tau2computeNchains`, temp, tau2_shape, prior_tau2, Nchains)
}

rhoquadformcomputeNchains <- function(Wtriplet, Wtripletsum, n_triplet, nsites, Nchains, phi, rho, tau2) {
    .Call(`_CARBayesST_rhoquadformcomputeNchains`, Wtriplet, Wtripletsum, n_triplet, nsites, Nchains, phi, rho, tau2)
}

Qdet <- function(Nchains, rho, Wstar_val) {
    .Call(`_CARBayesST_Qdet`, Nchains, rho, Wstar_val)
}

poissondevfit <- function(y, fitted, nsites, Nchains) {
    .Call(`_CARBayesST_poissondevfit`, y, fitted, nsites, Nchains)
}

poissonbetablockupdate <- function(nsites, beta, betaprop, lp_beta, lp_betaprop, offset, y, prior_meanbeta, prior_varbeta, Nchains, temps, p) {
    .Call(`_CARBayesST_poissonbetablockupdate`, nsites, beta, betaprop, lp_beta, lp_betaprop, offset, y, prior_meanbeta, prior_varbeta, Nchains, temps, p)
}

poissongammaupdate <- function(nsites, gamma, proposal, offset, offset_proposal, y, prior_meangamma, prior_vargamma, Nchains, temps) {
    .Call(`_CARBayesST_poissongammaupdate`, nsites, gamma, proposal, offset, offset_proposal, y, prior_meangamma, prior_vargamma, Nchains, temps)
}

poissonwupdate <- function(nsites, ntimes, w, offset, offset_proposal, w_proposal, y, lambda, Nchains, temps, begin, regbegin, Ntrends) {
    .Call(`_CARBayesST_poissonwupdate`, nsites, ntimes, w, offset, offset_proposal, w_proposal, y, lambda, Nchains, temps, begin, regbegin, Ntrends)
}

poissonphiupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntimes, phi, offset, y, tau2, rho, Nchains, temps, phi_tune, regbegin) {
    .Call(`_CARBayesST_poissonphiupdate`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntimes, phi, offset, y, tau2, rho, Nchains, temps, phi_tune, regbegin)
}

poissoncouplingAllupdate <- function(nsites, K, p, w, offset, beta, gamma, lambda, phi, rho, tau2, Wtripletsum, Wtriplet, Wbegfin, y, prior_meanbeta, prior_varbeta, prior_meantrends, prior_vartrends, prior_lambda, prior_tau2, swap, temps, begin, Ntrends, TrendSel) {
    .Call(`_CARBayesST_poissoncouplingAllupdate`, nsites, K, p, w, offset, beta, gamma, lambda, phi, rho, tau2, Wtripletsum, Wtriplet, Wbegfin, y, prior_meanbeta, prior_varbeta, prior_meantrends, prior_vartrends, prior_lambda, prior_tau2, swap, temps, begin, Ntrends, TrendSel)
}

binomialdevfit <- function(y, trials, probs, nsites, Nchains) {
    .Call(`_CARBayesST_binomialdevfit`, y, trials, probs, nsites, Nchains)
}

binomialbetablockupdate <- function(nsites, beta, betaprop, lp_beta, lp_betaprop, offset, y, failures, prior_meanbeta, prior_varbeta, Nchains, temps, p) {
    .Call(`_CARBayesST_binomialbetablockupdate`, nsites, beta, betaprop, lp_beta, lp_betaprop, offset, y, failures, prior_meanbeta, prior_varbeta, Nchains, temps, p)
}

binomialgammaupdate <- function(nsites, gamma, proposal, offset, offset_proposal, y, failures, prior_meangamma, prior_vargamma, Nchains, temps) {
    .Call(`_CARBayesST_binomialgammaupdate`, nsites, gamma, proposal, offset, offset_proposal, y, failures, prior_meangamma, prior_vargamma, Nchains, temps)
}

binomialwupdate <- function(nsites, ntimes, w, offset, offset_proposal, w_proposal, y, failures, lambda, Nchains, temps, begin, regbegin, Ntrends) {
    .Call(`_CARBayesST_binomialwupdate`, nsites, ntimes, w, offset, offset_proposal, w_proposal, y, failures, lambda, Nchains, temps, begin, regbegin, Ntrends)
}

binomialphiupdate <- function(Wtriplet, Wbegfin, Wtripletsum, nsites, ntimes, phi, offset, y, failures, tau2, rho, Nchains, temps, phi_tune, regbegin) {
    .Call(`_CARBayesST_binomialphiupdate`, Wtriplet, Wbegfin, Wtripletsum, nsites, ntimes, phi, offset, y, failures, tau2, rho, Nchains, temps, phi_tune, regbegin)
}

binomialcouplingAllupdate <- function(nsites, K, p, w, offset, beta, gamma, lambda, phi, rho, tau2, Wtripletsum, Wtriplet, Wbegfin, y, failures, prior_meanbeta, prior_varbeta, prior_meantrends, prior_vartrends, prior_lambda, prior_tau2, swap, temps, begin, Ntrends, TrendSel) {
    .Call(`_CARBayesST_binomialcouplingAllupdate`, nsites, K, p, w, offset, beta, gamma, lambda, phi, rho, tau2, Wtripletsum, Wtriplet, Wbegfin, y, failures, prior_meanbeta, prior_varbeta, prior_meantrends, prior_vartrends, prior_lambda, prior_tau2, swap, temps, begin, Ntrends, TrendSel)
}

optimise_graph <- function(adj, data, add = FALSE, remove = TRUE, remove_first = FALSE) {
    .Call(`_CARBayesST_optimise_graph`, adj, data, add, remove, remove_first)
}

